# Generated by Django 3.1.7 on 2021-05-03 15:39

from django.db import migrations, models
import django_cardano.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MintingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_id', models.CharField(max_length=64)),
                ('script_data', models.FileField(max_length=200, upload_to=django_cardano.models.file_upload_path)),
                ('signing_key', models.FileField(max_length=200, upload_to=django_cardano.models.file_upload_path)),
                ('verification_key', models.FileField(max_length=200, upload_to=django_cardano.models.file_upload_path)),
            ],
            options={
                'swappable': 'DJANGO_CARDANO_MINTING_POLICY_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('payment_address', models.CharField(max_length=128)),
                ('payment_signing_key', models.FileField(max_length=200, upload_to=django_cardano.models.file_upload_path)),
                ('payment_verification_key', models.FileField(max_length=200, upload_to=django_cardano.models.file_upload_path)),
                ('stake_address', models.CharField(max_length=128)),
                ('stake_signing_key', models.FileField(max_length=200, upload_to=django_cardano.models.file_upload_path)),
                ('stake_verification_key', models.FileField(max_length=200, upload_to=django_cardano.models.file_upload_path)),
            ],
            options={
                'abstract': False,
                'swappable': 'DJANGO_CARDANO_WALLET_MODEL',
            },
            managers=[
                ('objects', django_cardano.models.WalletManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_address', models.CharField(max_length=128)),
                ('inputs', models.JSONField(default=list)),
                ('outputs', models.JSONField(default=list)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('signed_tx_data', models.JSONField(blank=True, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Lovelace Payment'), (2, 'Token Payment'), (3, 'Token Mint'), (4, 'Token Consolidation')])),
            ],
        ),
    ]
