# Generated by Django 3.1.7 on 2021-04-24 15:23

from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MintingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField()),
                ('signed', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('payment_address', models.CharField(max_length=128)),
                ('payment_signing_key', django_cryptography.fields.encrypt(models.JSONField())),
                ('payment_verification_key', django_cryptography.fields.encrypt(models.JSONField())),
                ('stake_address', models.CharField(max_length=128)),
                ('stake_signing_key', django_cryptography.fields.encrypt(models.JSONField())),
                ('stake_verification_key', django_cryptography.fields.encrypt(models.JSONField())),
            ],
        ),
    ]
